adds content-security-policy to upgrade requests
firstandthird/hapi-csp-mixed pull request #5
Opened 2016-12-15 02:25 UTC by orthagonal

2016-12-15 15:54 UTC, jgallen23 commented on index.js
> +  policyHeaderKey: 'Content-Security-Policy',
lets make this dummy proof and have the option be `upgradeInsecureRequests: true`

2016-12-17 04:55 UTC, jgallen23 requested changes

2016-12-17 04:55 UTC, jgallen23 commented on test/test.mixed.js
> +lab.test('should add default headers to incoming requests of the indicated variety ', (allDone) => {
we need a test if its false

2016-12-17 04:55 UTC, jgallen23 commented on index.js
> +  headerKey: 'Content-Security-Policy-Report-Only',
should we change this to reportOnly: true? and if it's false, then have the key be `content-security-policy`?

2016-12-17 10:43 UTC, orthagonal commented on index.js
> +  headerKey: 'Content-Security-Policy-Report-Only',
I feel like it makes more sense if we have 'reportErrors' and 'upgradeInsecureRequests', and they can just set either or both of them to false.

2016-12-19 18:24 UTC, merged